version: '3'

services:
#  db:

  api:
    container_name: k9-backend
    image: node:23.0.0
    working_dir: /app/api
    env_file:
      - .env
    volumes:
      - './api:/app/api'
    ports:
      - '3000:3000'
      - '2500:3500'
      - '2001:3001'
    command: ['npm', 'run', 'start']
#    command:
#      - npm
#      - run
#      - start

  web:
    container_name: k9-frontend
    image: node:23.0.0
    working_dir: /app/web
    volumes:
      - './web:/app/web'
    ports:
      - '5000:5173'
    command: ['npm', 'run', 'dev']